Spoony-iOS/Spoony-iOS.xcodeproj/project.pbxproj, Spoony-iOS/Spoony-iOS/Resource/Components/SpoonyButton.swift, Spoony-iOS/Spoony-iOS/Resource/Extension/View+.swift, Spoony-iOS/Spoony-iOS/Resource/Helper/PopupModifier.swift
- close: #26 
- popup UI 구현
- SpoonyButton 터치 영역 수정
- 사진은 임의로 넣음 ~ 
|    구현 내용    |   IPhone 16 pro   | 
| :-------------: | :----------: | 
| GIF | <img src = "https://github.com/user-attachments/assets/fc34be92-e408-4eef-b2bb-f1966b4e350e" width ="250"> | 
| GIF | <img src = "https://github.com/user-attachments/assets/a2e8ffad-bc90-4810-9744-b85e137eb8a1" width ="250"> | 
| GIF | <img src = "https://github.com/user-attachments/assets/b6bd6449-74d6-4441-bc59-0171058e9113" width ="250"> | 
- 사용예시
```swift
struct Home: View {
@State private var isPresented: Bool = false
var body: some View {
VStack {
Text("Home")
.onTapGesture {
isPresented = true
}
}
.popup(popup: .useSpoon(action: {print("dd")}), isPresented: $isPresented)
}
}
```
- Popup이 추가될 경우 PopupType에 버튼 액션을 포함한 enum case 를 추가하고 …
=> Style/#26 popup UI 구현

Spoony-iOS/Info.plist, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/DetailView/Detail.swift
- close: #37
- 앱에서 원하는 키워드를 검색하여 버튼을 누르면 네이버 지도 검색으로 가는 로직을 구현 했습니다.
|    앱 없을때    |  앱 있을때   | 
| <img src = "https://github.com/user-attachments/assets/c8ecff63-05d9-4a08-bffc-3c40e06b906d" width ="350"> | <img src = "https://github.com/user-attachments/assets/631cdd3a-95c0-4de7-a981-813916e6e3bc" width ="350"> |
- 공식 문서를 읽고 앱 스킴을 따라서 하면 됩니다.
```swift
let url = URL(string: "nmap://search?query=\(searchName)&appname=\(appName)")!
let appStoreURL = URL(string: "http://itunes.apple.com/app/id311867728?mt=8")!
if UIApplication.shared.canOpenURL(url) {
UIApplication.shared.open(url)
} else {
UIApplication.shared.open(appStoreURL)
}
```
[네이버 맵 Scheme 공식문서](https://guide.ncloud-docs.com/docs/maps-url-scheme)
=> [Feat] #37 - 네이버 맵 검색 기능 구현 했습니다.

Spoony-iOS/Spoony-iOS/Resource/Components/SpoonyTextEditor.swift, Spoony-iOS/Spoony-iOS/Resource/Components/SpoonyTextField.swift, Spoony-iOS/Spoony-iOS/Resource/Extension/View+.swift
- close: #61 
- 텍스트 필드 로직 변경
- 다른 화면 터치시 키보드 내리기 위한 함수
- 이제 .icon의 경우 text 지우는 함수도 action에 구현해야합니다.
`View+`
```swift
extension View {
func hideKeyboard() {
UIApplication.shared.sendAction(#selector(UIResponder.resignFirstResponder), to: nil, from: nil, for: nil)
}
}
사용법
최상위뷰 
.onTapGesture {
hideKeyboard()
}
```
=> [Fix] 텍스트 필드 로직 수정

Spoony-iOS/Spoony-iOS/Resource/Components/BottomSheet/BottomSheetList.swift
- close: #54 
- 바텀시트 스크롤 영역따라 같이 올라가고 내려가기
- 하단영역 여백 추가하여 맞추기
| GIF | <img src = "https://github.com/user-attachments/assets/cff00ba4-8057-48b1-8447-0b1af7a6251c" width ="250"> | <img src = "https://github.com/user-attachments/assets/7b6f56bd-7c8f-4eaa-ac0e-3f40ca9b1f61" width ="250"> |
- 어쩌구저쩌구
```swift
.background(
GeometryReader { itemGeometry in
Color.clear.onAppear {
if index == 0 {
firstItemFrame = itemGeometry.frame(in: .named("scrollView"))
}
}
.onChange(of: itemGeometry.frame(in: .named("scrollView"))) { _, newFrame in
if index == 0 {
firstItemFrame = newFrame
// 첫 번째 셀의 위치에 따라 바텀시트 상태 변경
let threshold: CGFloat = -30
if newFrame.minY < threshold && …
```
=> [Style] 바텀시트 제스처 따라 수정

Spoony-iOS/Spoony-iOS/Resource/Components/Navigation/CustomNavigationBar.swift, Spoony-iOS/Spoony-iOS/Resource/Components/Navigation/NavigationBarStyle.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/DetailView/DetailView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/Explore.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Home/Home.swift
- close: #66 
- 네비게이션 UI를 제대로 수정합니다.
| GIF | <img src = "
- 네비게이션 스타일
```swift
// 검색 관련
case searchContent //지도에서 왼쪽에 칩 있는거
case search(showBackButton: Bool = true) // 뒤로가기 버튼 표시 여부 추가
case searchBar
// 위치 관련
case locationTitle    // 위치 제목 + 오른쪽 X 버튼
case locationDetail   // 탐색 리스트 - 현위치 + > + 오른쪽 칩 아이콘
// 상세 화면 관련
case detail(isLiked: Bool)         // < + 가운데 타이틀 사용 (신고하기)
case detailWithChip(count: Int)    // < + 오른쪽 칩 (가운데 타이틀 없음)
// 백 버튼 표시 여부
var showsBackButton: Bool {
switch self {
case .locationDetail, .locationTitle, .searchContent:
return false
case .search(let showBackButton):
return showBackButton
default:
return true
}
}
```
=> [Style] 네비게이션 디테일 UI 추가

Spoony-iOS/Spoony-iOS/Network/Auth/UserManager.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Search/SearchView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Search/Views/SearchResultRow.swift
- close: #108 
- userdefault를 추가해서 검색기록을 저장합니다
- 스크롤뷰를추가하여 검색기록이 많아졋을 경우 스크롤이 가능해지게 햇습니다.
| GIF | <img src = "https://github.com/user-attachments/assets/f72e6a08-c9f5-4f9e-afc9-2ba0a1ee5c36" width ="250"> | <img src = "" width ="250"> |
기본적인 내용UserDefaults 이여서 코드 설명은 없습니다.
저장내용에 제한이 없는것은 원래 기획의도가 그렇습니다.
=> feat:userdefault 추가

Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/RegisterIntent.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/RegisterState.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/RegisterStore.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/View/InfoStepView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/View/Register.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/View/ReviewStepView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/SpoonyTabView.swift
- close: #99 
- MVI 리펙토링
`InfoStepView`
- 이전 코드는 삭제 부분만 ForEach문을 통해 Index로 접근하여 사용하였는데 get, get을 통한 바인딩을 하니까 
ForEach 내부에서 text를 변경하게 되어 인덱스 오류가 발생하였습니다. 그래서 배열 Text를 다루기 위한 구조체를 
선언하고 UUID 값을 할당하여 해당 id를 통해 갱신 및 삭제가 이루어지도록 구현했습니다.
```
Array(store.state.recommendTexts.enumerated())를 사용하면 인덱스가 offset으로 전달됩니다. 
그러나 배열을 수정할 때(예: 요소를 변경하거나 삭제) ForEach가 요소를 다시 갱신하면서 배열의 크기나 순서가 변경될 수 있습니다. 
이때, 배열이 수정되면 index 값이 더 이상 유효하지 않게 되어 인덱스 오류가 발생할 수 있습니다.
```
```swift
private var recommendSection: some View {
VStack(alignment: .leading, spacing: 0) {
Text("추천 메뉴를 알려주세요")
.font(.body1sb)
.foregroundStyle(.spoonBlack)
.padding(.bottom, 12)
VStack(spacing: 8) {
ForEach(store.state.recommendTexts, id: \.id) { text in
SpoonyTextField(
text: Binding(get: {
text.text
}, set: { newValue in …
```
=>  Refactor/#99 등록뷰 MVI 변경

Spoony-iOS/Spoony-iOS/Resource/Components/SpoonyTextField.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/RegisterIntent.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/RegisterState.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/RegisterStore.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/View/InfoStepView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/View/ReviewStepView.swift
- close: #137 
- PhotosPicker의 maxSelectionCount 이상의 사진이 선택되는 버그 수정
- 특정 특수문자 입력 안되는 버그 수정
- 사진 선택 후 키보드 다시 올리오는 현상 수정
`RegisterStore`
- 새로 선택된 아이템 개수 검사하여 연타 입력시 추가되는 현상 방지
```swift
private func validateSelectedPhotoCount(item: [PhotosPickerItem]) {
if item.count > state.selectableCount {
state.pickerItems = Array(item.prefix(state.selectableCount))
state.selectableCount = 0
}
} 
```
`ReviewStepView`
- PhotosPickerItem의 변화를 감지하여 바로 추가 로직을 타지 않고 필터링 되도록 구현
```swift
PhotosPicker() {
생략
}
.onChange(of: store.state.pickerItems, { _, newValue in
store.dispatch(.didTapPhoto(newValue))
})
```
추천 메뉴 플러스 버튼과 마이너스 버튼 연타시 생기는 버그는 현재 재현이 안되어 나중에 다시 하겠습니다.
=> [Fix] #137 RegisterView 버그 수정 

Spoony-iOS/Spoony-iOS/Network/Model/CardPlaceModel.swift, Spoony-iOS/Spoony-iOS/Network/Model/FeedResponse.swift, Spoony-iOS/Spoony-iOS/Network/Model/MapFocusResponse.swift, Spoony-iOS/Spoony-iOS/Resource/Components/BottomSheet/FixedBottomSheetView.swift, Spoony-iOS/Spoony-iOS/Resource/Tab/Model/ViewType.swift, Spoony-iOS/Spoony-iOS/Resource/Tab/NavigationManager.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/DetailView/DetailService.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/DetailView/DetailState.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/DetailView/DetailView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/DetailView/DetailViewStore.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/Explore.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/Model/FeedEntity.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Home/Components/PlaceHolderCardView/PlaceCard.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Home/Home.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Home/HomeViewModel.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/Model/DetailModel.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/RegisterStore.swift
- close: #153
- 네비게이션 탐색 연결 했습니다.
- 떠먹기 기능 안되는 문제 해결 했습니다.
| 탐색 -> 상세 + 떠먹기 기능  |
| :-------------: | 
| <img src = "https://github.com/user-attachments/assets/438f94ea-f7f6-4c6c-b63f-9157713600ff" width ="250"> |
- 기존 코드 Concurrency 적용 했습니다.
떠먹기 기능이 completion 작동이 안되기 때문에 이 부분만 수정 했습니다. 나머지도 나중에 해결 하겠습니다.
```swift
func scoopReview(userId: Int, postId: Int) async throws -> Bool {
return try await withCheckedThrowingContinuation { continuation in
detailProvider.request(.scoopReview(userId: Config.userId, postId: postId)) { result in
switch result {
case .success(let response):
do {
_ = try response.map(BaseResponse<BlankData>.self)
return continuation.resume(returning: true)
} catch {
continuation.resume(throwing: error)
}
case .failure(let error): …
```
=> [Feat] #153 -  네비게이션 탐색 상세 연결 했습니다.

Spoony-iOS/Spoony-iOS/Source/Feature/Register/Components/ChipsContainerView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/RegisterIntent.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/RegisterState.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/RegisterStore.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/View/InfoStepView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/View/Register.swift
- close: #149 
- 키보드 활성화 여부에 따른 자동 스크롤 구현
- QA 카테고리 칩 순서 수정 사항 반영
https://github.com/user-attachments/assets/eed0c5d8-002b-4b69-b8cd-03db816603c7
`InfoStepView`
- ScrollViewReader의 proxy를 이용하여 자동 스크롤 구현
- .onAppear 시에 키보드 활성화/비활성화를 감지하도록 하여 키보드 keyboardHeight 업데이트
- keyboardHeight에 따라 bottom 기준으로 padding 추가
```swift
ScrollViewReader { proxy in
VStack { ... }
.onAppear {
NotificationCenter.default.addObserver(
forName: UIResponder.keyboardWillShowNotification,
object: nil,
queue: .main
) { notification in
if let frame = notification.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? CGRect {
withAnimation(.smooth) {
store.dispatch(.updateKeyboardHeight(frame.height))
}
}
}
NotificationCenter.default.addObserver(
forName: UIResponder.keyboardWillHideNotification,
object: nil,
queue: …
```
=>  [Feat] #149 - 키보드 활성화 여부에 따른 자동 스크롤 구현

Spoony-iOS/Spoony-iOS/Network/TargetType/DetailTargetType.swift, Spoony-iOS/Spoony-iOS/Resource/Helper/ToastModifier.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/DetailView/DetailService.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/DetailView/DetailState.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/DetailView/DetailView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/DetailView/DetailViewStore.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/DetailView/UserInfoModel.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/Model/DetailModel.swift
- close: #174
- 탐색 상세뷰에, 유저 정보를 불러오는 API를 연결 했습니다. (빨간색 네모친 부분)
<   탐색 상세 뷰   >
`DetailService 파일에 API 함수 추가 했습니다.`
```swift
func getUserInfo(userId: Int) async throws -> UserInfoModel {
return try await withCheckedThrowingContinuation { continuation in
detailProvider.request(.getUserInfo(userId: userId)) { result in
switch result {
case .success(let response):
do {
let result = try response.map(BaseResponse<UserInfoModel>.self)
if let result = result.data {
return continuation.resume(returning: result)
} else {
print("옵셔널 바인딩 X")
}
} catch {
continuation.resume(throwing: error)
}
case .failure(let error):
continuation.resume(throwing: error)
}
}
}
}
```
1. 전체적으로 코드가 너무 정리가 안되어있네요!!! 리팩토링을 해야겠어요
2. Concurrency를 너무 정형화 되어있게 사용만 하는거 같아요, 왜 이렇게 썼는지 생각 하면서 구현을 해야 겠어요!
=> [Feat] #174 - 유저 프로필을 받아오는 API를 연결 했습니다.

Spoony-iOS/Spoony-iOS/Source/Feature/Home/Cache/CachedImage.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Home/Cache/CachedImageLoader.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Home/Cache/ImageCacheManager.swift
- close: #193 
- 메모리 누수 해결
- 데이터 레이스 해결
- 구조화된 동시성 사용
메모리 누수 관련해서 이전 코드에서 `diskIOQueue`에서 싱글톤으로 참조중이였기에 작업이완료되지 않는 상황에서 참조 사이클이 발생할 잠재적 위험을 확인했습니다.
또한, 메인스레드에서의 업데이트, Concurrency등 더 발전시킬 코드들이 있어 작업을 했습니다
actor의 개념이 나와서 혼란스러우실수도 있겟지만
해당 PR 에서는 Concurrency에 대해 직접적으로 설명하지는 않겟습니다.
코멘트로 잘 모르는 부분이나 이해가 되지 않는 부분들 남겨주시면 코멘트 부분에서 설명해드릴게요!
좀더 깊은 이해를 위해서는 actor에 대해서 먼저 학습을 하고 오셔도 좋을것같습니다.
```swift
func load() async {
loadTask?.cancel()
loadTask = Task {
do {
// 작업 내부에서 취소 확인
if !Task.isCancelled {
self.image = cachedImage
}
// 네트워크 요청에서 취소 핸들러 사용
let imageData = try await withTaskCancellationHandler {
try await URLSession.shared.data(from: url).0
} onCancel: {
// 취소 처리 - URLSession 태스크는 자동으로 취소
}
// 취소 확인 후 작업 계속
guard !Task.isCancelled else { return }
// 결과 처리에서도 취소 확인
if !Task.isCancelled { …
```
=> [Refactor] #193 actor도입과 메모리 누수 해결

Spoony-iOS/Spoony-iOS/Network/TargetType/DetailTargetType.swift, Spoony-iOS/Spoony-iOS/Network/TargetType/HomeTargetType.swift, Spoony-iOS/Spoony-iOS/Resource/Tab/NavigationManager.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Data/DataMapping/ReviewDetailResponseDTO.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Data/DataMapping/UserInfoResponseDTO.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Data/Repository/DetailRepository.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Data/Service/DetailService.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Domain/RepositoryInterface/DetailRepositoryInterface.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Domain/UseCase/DetailUseCase.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Presentation/DetailView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Presentation/DetailViewStore.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Presentation/MockDetailViewStore.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Presentation/PostFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Presentation/PostView.swift
- close: #190
- DetailView -> PostView로 이름 변경 했습니다.
- PostFeature (TCA) 를 구현 했습니다.
|    구현뷰    |   IPhone 15 pro   | 
| 상세뷰 | <img src = "https://github.com/user-attachments/assets/e65d520e-a8ed-44fc-ba23-b4e5c86578bf" width ="250"> | 
1. `PostFeature`
- PostView에서 사용하는 메인 로직이 들어갑니다.
`DropDown` 액션, `ToastAction` 모든 액션을 넣어서 테스트를 해보려고 했는데, 아직 등록이랑 로그인 등 고려할게 많아서 전부 구현하진 않았습니다.
주요 액션만 아래처럼 구현했습니다.
```swift
enum Action {
case viewAppear(postId: Int)
case fetchInitialResponse(Result<ReviewDetailModel, APIError>)
case scoopButtonTapped
case scoopButtonTappedResponse(isSuccess: Bool)
case zzimButtonTapped(isZzim: Bool)
case zzimButtonResponse(isScrap: Bool)
case error
}
```
- Reducer 구현은 아래처럼 해두었습니다.
TCA 튜토리얼을 봤을때, 서버통신과 값 적용하는 것을 따로따로 case로 분리해서 하는 것을 보고 저도 …
=> [Refactor] #190 - 상세 뷰 TCA 리팩토링 진행 했습니다.

Spoony-iOS/Spoony-iOS/Resource/Components/SpoonyTextField.swift
- close: #205 
- ForEach를 통해 recommendTexts를 반복해서 SpoonyTextField를 생성후 바인딩 해줬는데 
이 과정에서 삭제 아이콘을 연속 클릭시 삭제후 recommendTexts가 ForEach 부분에 반영되기 전에
이미 삭제된 recommendText에 접근하게 되어 인덱스 오류가 발생했습니다.
SpoonyTextField에 disabled 값을 설정하여 일정 시간 뒤에 클릭이 가능해지도록 하여 수정했습니다.
=> fix: icon 버튼 연속 액션 호출 수정

Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/TestScenes/MyPageCoordinator/MyPageCoordinator.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/MyPageView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/AccountManagement/AccountManagementFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/AccountManagement/AccountManagementView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/BlockedUsersFeature/BlockedUsersFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/BlockedUsersFeature/BlockedUsersView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/InquiryFeature/InquiryFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/InquiryFeature/InquiryView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/LocationFeature/LocationServicesFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/LocationFeature/LocationServicesView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/PrivacyPolicy/PrivacyPolicyFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/PrivacyPolicy/PrivacyPolicyView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/SettingFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/SettingsView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/TermsOfServiceFeature/TermsOfServiceFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/TermsOfServiceFeature/TermsOfServiceView.swift
- close: #249 
- 마이페이지에 딸려오는 설정 뷰 코디네이터와 뷰들을 연결햇습니다
- 뷰 내 뷰 는 다음 PR에~ ( 코드가 너무 길어짐
| GIF | <img src = "https://github.com/user-attachments/assets/fd2fe197-9bd9-4e6f-ae9f-b15e516e8319" width ="250"> | <img src = "" width ="250"> |
각 뷰 내에 있는 내용들 (계정관리, 서비스 이용약관 내부 등,,)은 전부 GPT로 깡통만 만든거니 신경쓰지 마세요~
=> [Style/#249] MyPage 뷰연결

Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/TestScenes/MyPageCoordinator/MyPageCoordinator.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/MyPageView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/AccountManagement/AccountManagementFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/AccountManagement/AccountManagementView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/AccountManagement/CustomAlertView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/AccountManagement/LogOut/LogoutFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/AccountManagement/LogOut/LogoutView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/AccountManagement/withdraw/WithdrawFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/AccountManagement/withdraw/WithdrawView.swift
- close: #268 
- 회원탈퇴뷰 구현
- 로그아웃뷰 구현
- 내부 TCA 로직 수현
| GIF | <img src = "https://github.com/user-attachments/assets/3241e9d9-d966-4cb1-a1e3-df7a5bf4eda1" width ="250"> | <img src = "" width ="250"> |
하 API 언제붙임
=> [Style/#268] 회원탈퇴뷰 구현

Spoony-iOS/Spoony-iOS/Network/Auth/UserManager.swift, Spoony-iOS/Spoony-iOS/Network/Base/Providers.swift, Spoony-iOS/Spoony-iOS/Network/DependencyKey/SpoonDrawServiceKey.swift, Spoony-iOS/Spoony-iOS/Network/Model/SpoonDrawResponse.swift, Spoony-iOS/Spoony-iOS/Network/Service/HomeService/HomeService.swift, Spoony-iOS/Spoony-iOS/Network/Service/Service.swift, Spoony-iOS/Spoony-iOS/Network/Service/SpoonDrawService.swift, Spoony-iOS/Spoony-iOS/Network/TargetType/HomeTargetType.swift, Spoony-iOS/Spoony-iOS/Network/TargetType/SpoonDrawTargetType.swift, Spoony-iOS/Spoony-iOS/Resource/Components/SpoonyDraw/SpoonDrawPopupView.swift, Spoony-iOS/Spoony-iOS/Resource/Extension/DependencyValues+.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Home/Home.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Home/MapFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Attendance/AttendanceFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Attendance/AttendanceView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Attendance/SpoonAttendanceView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/MyPageView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/AccountManagement/withdraw/WithdrawFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Search/SearchFeature/SearchFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Search/Views/SearchView.swift
- close: #320 
- 지도화면에서 뒤로가기시 이전 네비게이션 타입으로 이동하는 문제를 해결
- 스푼 카운트API 연결하여 첫진입시 스푼뽑기 구현
- 출석체크뷰에서 API로 뽑기 확인 뷰 구현
- 기타 불필요 코드 삭제
| GIF | <img src = "https://github.com/user-attachments/assets/29e526ec-1671-4d4f-9ef6-b3a949205cb3" width ="250"> | <img src = "" width ="250"> |
=> [Fix/#320] 고장난지도뷰고치기

Spoony-iOS/Spoony-iOS/Network/Auth/KeychainManager.swift, Spoony-iOS/Spoony-iOS/Network/Auth/TokenAuthenticator.swift, Spoony-iOS/Spoony-iOS/Network/Auth/TokenCredential.swift, Spoony-iOS/Spoony-iOS/Network/Base/Providers.swift, Spoony-iOS/Spoony-iOS/Network/Model/AuthModel/RefreshResponse.swift, Spoony-iOS/Spoony-iOS/Network/Service/AuthService/AuthService.swift, Spoony-iOS/Spoony-iOS/Network/Service/AuthService/RefreshService.swift, Spoony-iOS/Spoony-iOS/Network/TargetType/AuthTargetType.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/AppCoordinator/AppCoordinatorView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Auth/AuthenticationManager.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Login/LoginFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Setting/AccountManagement/AccountManagementFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Setting/AccountManagement/withdraw/WithdrawFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Onboarding/OnboardingFeature.swift
- close: #335 
- refresh만을 실행하는 service를 싱글톤으로 구현하였습니다
- test는 not yet... 
`TokenAuthenticator`
- refresh가 호출되기까지 흐름을 주석으로 정리하였습니다
```swift
// 1) 요청하기 전 호출되어 헤더에 JWT 토큰 추가
func apply(_ credential: TokenCredential, to urlRequest: inout URLRequest) {
urlRequest.headers.add(.authorization(bearerToken: credential.accessToken))
}
// 2) api 요청 후 응답의 상태코드가 401이면 true를 리턴하며 refresh 프로세스 계속 진행
func didRequest(_ urlRequest: URLRequest, with response: HTTPURLResponse, failDueToAuthenticationError error: any Error) -> Bool {
return response.statusCode == 401
}
// 3) 헤더의 token과 credential의 token을 비교
// 같은 경우: token 만료 -> refresh()
// 다른 경우: apply부터 다시 호출하여 최신 token으로 재시도
func isRequest(_ urlRequest: URLRequest, authenticatedWith credential: TokenCredential) -> Bool {
let token = …
```
=> [Feat/#335] 자동 로그인 구현

Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Edit/EditProfileFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Following/FollowFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Following/FollowResponseModel.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Presentation/PostFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Presentation/PostView.swift
=> [Fix/#361] 자잘한 QA 개선

Spoony-iOS/Spoony-iOS/Resource/Components/Navigation/CustomNavigationBar.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/TabRootCoordinator/TabRootCoordinator.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Presentation/PostFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Presentation/PostView.swift
- close: #391 
- 스푼 뽑기 기능을 추가 하였습니다.
|    스푼 처음 뽑았을 경우    |   스푼을 이미 뽑았을 경우(출첵 뷰로만 이동해야함 모달 뜨면 안돼 ⛔️ )   |  
| ![ScreenRecording_06-16-2025 22-54-28_1](https://github.com/user-attachments/assets/73a9831d-91f0-4e57-842e-133531a527f9)  |   ![ScreenRecording_06-16-2025 22-45-45_1](https://github.com/user-attachments/assets/35c8fa1a-1545-48ea-9ced-d1836fb5899d) |
`PostFeature.swift`
-> `routeToAttendanceView` 로 이동
-> `SpoonDrawPopupView`
```swift
case .spoonTapped:
print("🔍 isFirstVisitOfDay: \(UserManager.shared.isFirstVisitOfDay())")
if !UserManager.shared.isFirstVisitOfDay() { // 지훈쌤이 스푼 뽑았으면 true 라고 했음
print("🔍 스푼 뽑기를 안헀으면 팝업 표시")
return .send(.setShowDailySpoonPopup(true))
} else {
print("🔍 스푼 뽑기을 했으면 AttendanceView로 이동")
return …
```
=> [Feat/#391] 스푼 박살내기 구현 90% 완료

Spoony-iOS/Spoony-iOS.xcodeproj/project.pbxproj, Spoony-iOS/Spoony-iOS/Network/NetworkingMacros/.gitignore, Spoony-iOS/Spoony-iOS/Network/NetworkingMacros/Package.swift, Spoony-iOS/Spoony-iOS/Network/NetworkingMacros/Sources/NetworkingMacros/NetworkingMacros.swift, Spoony-iOS/Spoony-iOS/Network/NetworkingMacros/Sources/NetworkingMacrosClient/main.swift, Spoony-iOS/Spoony-iOS/Network/NetworkingMacros/Sources/NetworkingMacrosMacros/NetworkingMacrosMacro.swift, Spoony-iOS/Spoony-iOS/Network/Service/HomeService/HomeService.swift
- close: #373 
- @macro를 사용하여 반복코드를 줄였습니다.
저도 처음 사용해보는거긴 한데 공부겸 공유겸 좀 깊게 파봣습니다.
동작 원리가 궁금하다면 처음부터 글을 봐주셔도 좋고 사용법이랑 뭐가 바뀐건지 보려면 선생님들 코드에 적용하는 방법 부터 보셔도 됩니다.
매크로는 **Swift 언어를 사용자에 맞춰서 커스텀해주는 역할**을 합니다.
WWDC에서 소개한 예시 중 제일 이해가 잘되는 예시는 **Codable**과 관련된 예시인데
우리가 보통 Codable을 채택해서 쓸 때, 따로 CodingKeys를 지정해 줄 필요가 없다면 아래처럼 간단하게만 작성하면 됩니다.
```rust
struct Example: Codable {
let id: String
let fullName: String
}
```
그치만 사실 `fullName`변수가 json데이터에는 `full_name`으로 온다면, CodingKeys를 추가해주어야죠!
```swift
struct Example: Codable {
let id: String
let fullName: String
enum CodingKeys: String, CodingKey {
case id
case fullName = "full_name"
}
init(from decoder: Decoder) throws { ... }
func encode(to: encoder: Encoder) throws { ... }
}
```
됫다!
그럼 CodingKeys를 안쓸때는 이것들이 어캐 동작하는걸까요?
Codable을 사용하면, Swift가 자동으로 관련 코드를 …
=> [Refactor/#373] @macro를 사용한 반복코드 제거

Spoony-iOS/Spoony-iOS/Mixpanel/Events/ExploreEvents.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/Filtering/SortBottomSheet.swift
- close: #441 
- mixpanel key로 사용하고 있던 값을 분리해줬습니다
=> fix: #441 필터링 많이 저장 순 안되는 버그 해결
