SpoonMe/.swiftlint.yml, SpoonMe/SpoonMe.xcodeproj/project.pbxproj
- #8 
1. SwiftLint 추가 했습니다.
- disabled_rules 은 말 그대로 안지켜도 될 규칙 이라고 생각 하면 됩니다.
기본적으로 disabled_rules를 설정하지 않으면 모든 규칙이 적용 되서 좀 깐깐해져요
- excluded 는 파일 경로를 쓰면 해당하는 경로 파일에는 lint 적용을 하고 싶지 않다! 라고 이해하면 됩니다.
- 아래를 보시면 파일이 1200자가 넘으면 컴파일 에러를 뜨게 했어요
```
file_length:
warning: 600 # 600줄 넘어가면 경고 입니다 ^_^
error: 1200 # 1200줄 은 진짜 에러 입니다 ^^ 혼나요
```
- 강제 캐스팅은 경고만 주는걸로 일단 해놨습니다.
[참고링크](https://thingjin.tistory.com/entry/iOS-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EC%97%90-SwiftLint-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0)
- Resolved: #8
=> [Setting] #8 - SwiftLint 추가 했습니다.

Spoony-iOS/Spoony-iOS/Resource/Components/SpoonyButton.swift, Spoony-iOS/Spoony-iOS/Resource/Tab/NavigationManager.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/DetailView/Detail.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/Explore.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/FilterBottomSheet.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/LocationPickerBottomSheet.swift
- close: #43 
- 정렬 바텀시트 
- 장소 선택 바텀시트
- 버튼 case 추가
- 폴더 및 파일 네이밍 수정 Quest -> Explore
|    구현 내용    |   IPhone 16 pro   |   iPhone 13 mini  |
| GIF | <img src = "https://github.com/user-attachments/assets/0c993b2f-fc63-4309-ae6e-d74e8f4fb3ca" width ="250"> | <img src = "https://github.com/user-attachments/assets/34acc0a5-ee50-4540-b2dd-68b7a03dbee9" width ="250"> |
|    구현 내용    |   IPhone 16 pro   |   iPhone 13 mini  |
| GIF | <img src = "https://github.com/user-attachments/assets/120b679e-cb17-46c6-8688-565615bd232c" width ="250"> | <img src = "https://github.com/user-attachments/assets/050bdc9f-9860-4abe-ad85-6855d995e79a" width ="250"> |
=> Style/#43 bottomsheet UI

Spoony-iOS/Spoony-iOS/Source/Feature/Home/Components/PlaceHolderCardView/PlaceCardsContainer.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Home/Home.swift
=> hotfix: #51 conflict goruf

Spoony-iOS/Spoony-iOS.xcodeproj/project.pbxproj, Spoony-iOS/Spoony-iOS/Resource/Components/DropDownMenu.swift, Spoony-iOS/Spoony-iOS/Resource/Helper/ToastModifier.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/DetailView/DetailView.swift
- close: #53 
- DetailView 공개/비공개 모드 구현
- DetailView 드롭다운 구현
- Lotties 설치
|    공개 모드    |   비공개 모드 | 
| <img src = "https://github.com/user-attachments/assets/ab07f46e-cf78-447e-9a0a-5e46d2c34447" width ="350"> | <img src = "https://github.com/user-attachments/assets/a7e6dab8-d273-4fc9-8b33-cb5af3d37871" width ="350"> |
- ### DropDown 사용 방법
1. items 을 넣는다. (드롭 다운 메뉴 갯수)
2. isPresented `State` 변수를 관리 해준다
3. Layout을 설정해준다.
```swift
DropDownMenu(items: ["수정하기", "신고하기"], isPresented: $isPresented) { menu in
print("선택된 메뉴: \(menu)")
isPresented = false
}
.frame(alignment: .topTrailing)
.padding(.top, 48.adjustedH)
.padding(.trailing, 20.adjusted)
```
- ### 공개/비공개 처리
privateMode 상태 변수로 관리하게 했습니다. 더 좋은 구조는 MVI 리팩이나, 서버 구현때 다시 고민해 보겠음.
버튼 분기처리는 아래 처럼 했습니다. 참 쉽죠? …
=> [Feat] #53 - DetailView 비공개, 공개 모드, 드롭다운 메뉴 구현 했습니다.

Spoony-iOS/Spoony-iOS/Resource/Components/SpoonyTextEditor.swift, Spoony-iOS/Spoony-iOS/Resource/Components/SpoonyTextField.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/RegisterStore.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/View/InfoStepView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/View/Register.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/View/ReviewStepView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Report/Report.swift
- close: #80 
- 2단계 화면 구현
- 주리 뷰 스크롤뷰로 수정
- 텍스트 필드, 텍스트 에디터 분기 처리 추가
- iPhone 15 Pro
https://github.com/user-attachments/assets/1922750d-6532-44f8-9171-60d027964737
- iPhone mini
https://github.com/user-attachments/assets/523e0a4a-2763-42cf-b5a5-4a4a5afdad1a
이미지 비동기 처리를 통해 배열에 추가했는데 해당 배열 접근 시 경고가 뜹니다...
=>  [Style] #80 등록 2단계 뷰 구현

.gitignore, Spoony-iOS/Spoony-iOS/Network/Auth/UserDefaultWrapper.swift, Spoony-iOS/Spoony-iOS/Network/Auth/UserManager.swift, Spoony-iOS/Spoony-iOS/Network/Base/BaseResponse.swift, Spoony-iOS/Spoony-iOS/Network/TargetType/DetatilTargetType.swift, Spoony-iOS/Spoony-iOS/Network/TargetType/ExploreTargetType.swift, Spoony-iOS/Spoony-iOS/Network/TargetType/HomeTargetType.swift, Spoony-iOS/Spoony-iOS/Network/TargetType/RegisterTargetType.swift, Spoony-iOS/Spoony-iOS/Network/TargetType/TargetType.swift
- close: #94
- Moya 라이브러리에서 통신 Method를 정의하는 TargetType을 구현 했습니다.
아래 초기화 되어 있는 sampleData, validationType 속성 말고는 필수로 구현 해주어야 합니다.!
두개의 속성이 언제 사용되는 지는 추후에 알려드리겠습니다!
⭐️ path, task, headers 가 서버 명세서가 달라질 수 있으니 꼭 변동 사항을 적용해주셔야 합니다! ⭐️
```swift
public protocol TargetType {
/// The target's base `URL`.
var baseURL: URL { get }
/// The path to be appended to `baseURL` to form the full `URL`.
var path: String { get }
/// The HTTP method used in the request.
var method: Moya.Method { get }
/// Provides stub data for use in testing. Default is `Data()`.
var sampleData: Data { get }
/// The type of HTTP task to be performed.
var task: Task { get }
/// The type of validation to perform on the request. Default is `.none`.
var validationType: ValidationType { get }
/// The headers to be used in the …
```
=> [Setting] #94 - network 통신 TargetType을 세팅 했습니다.

Spoony-iOS/Spoony-iOS/Resource/Components/BottomSheet/FixedBottomSheetView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Home/Components/PlaceHolderCardView/PlaceCardsContainer.swift
- close: #105 
- 네비게이션 로직 추가
https://github.com/user-attachments/assets/c77188dd-3d2b-4174-9c0c-a397b24ef80b
=> Feat/#105 네비게이션 이동로직 추가

Spoony-iOS/Spoony-iOS/Network/Base/BaseResponse.swift, Spoony-iOS/Spoony-iOS/Network/Model/FeedResponse.swift, Spoony-iOS/Spoony-iOS/Network/Service/ExploreService.swift, Spoony-iOS/Spoony-iOS/Network/TargetType/ExploreTargetType.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/Explore.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/ExploreCell.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/FilterBottomSheet.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/LocationPickerBottomSheet.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/Store/ExploreStore.swift
- close: #101
- API 연결을 위한 네트워크 세팅
- BaseResponse 수정 
- store 생성하면서 view 로직 refactoring
- CategoryColorResponse 구조체는 공유해도 좋을 것 같습니다 !
=> Feat/#101 탐색 - 사용자 피드 조회 API

Spoony-iOS/Spoony-iOS/Network/Base/Providers.swift, Spoony-iOS/Spoony-iOS/Network/Base/SpoonyLoggingPlugin.swift, Spoony-iOS/Spoony-iOS/Network/TargetType/DetailTargetType.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/DetailView/DetailView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/Model/DetailModel.swift
- close: #104
- `MoyaLoggingPlugIn` 구현 했습니다.
URL, Header, Method 등 정보를 문자열로 로깅할 수 있는 class 를 구현 했습니다.
아래 처럼 로그를 확인 할 수 있어요!
플러그인 사용 방법은 Provider 생성자에 넣어주면 됩니다.
```swift
self.init(plugins: [SpoonyLoggingPlugin()])
```
=> [Setting] #104 - NetworkLoggerPluggin구현 했습니다.

Spoony-iOS/Spoony-iOS/Network/Model/SpoonResponse.swift, Spoony-iOS/Spoony-iOS/Network/Service/HomeService/HomeError.swift, Spoony-iOS/Spoony-iOS/Network/Service/HomeService/HomeService.swift, Spoony-iOS/Spoony-iOS/Resource/Components/Navigation/CustomNavigationBar.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Home/Home.swift
- close: #114 
- APIError 파일을 추가해서 에러 로깅을 확인합니다.
- API 연결을 햇습니다.
```swift
enum APIError: LocalizedError {
case invalidResponse
case responseError
case noData
case decodingError        
var errorDescription: String? {
switch self {
case .invalidResponse:
return "Invalid server response"
case .responseError:
return "Server returned an error"
case .noData:
return "No data available"
case .decodingError:
return "Failed to decode response"
}
}
}
func fetchSpoonCount(userId: Int) async throws -> Int {
return try await withCheckedThrowingContinuation { continuation in
Providers.homeProvider.request(.getSpoonCount(userId: …
```
=> Feat/#114 떠먹은 listChip API 연결

Spoony-iOS/Spoony-iOS/Network/Model/ReportRequest.swift, Spoony-iOS/Spoony-iOS/Network/Service/ReportService.swift, Spoony-iOS/Spoony-iOS/Network/TargetType/ExploreTargetType.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Report/Report.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Report/Store/ReportStore.swift
- close: #123 
- 신고 API 연결
`Report`
- 이번에는 Task로 묶은 함수 없이 view에서 함수 접근해서 사용했습니다...
```swift
Task {
try await store.postReport(postId: 1, description: text)
navigationManager.popup = .reportSuccess(action: {
navigationManager.pop(2)
})
}
```
=> Feat/#123 신고 API 연결

Spoony-iOS/Spoony-iOS/Network/Service/RegisterService/RegisterModel/RegisterCategoryResponse.swift, Spoony-iOS/Spoony-iOS/Network/Service/RegisterService/RegisterModel/SearchPlaceResponse.swift, Spoony-iOS/Spoony-iOS/Network/Service/RegisterService/RegisterModel/ValidatePlaceRequest.swift, Spoony-iOS/Spoony-iOS/Network/Service/RegisterService/RegisterModel/ValidatePlaceResponse.swift, Spoony-iOS/Spoony-iOS/Network/Service/RegisterService/RegisterService.swift, Spoony-iOS/Spoony-iOS/Network/TargetType/RegisterTargetType.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/Components/CategoryChipsView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/Components/ChipsContainerView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/Components/PlaceInfoCell.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/Model/CategoryChip.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/Model/PlaceInfo.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/RegisterIntent.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/RegisterState.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/RegisterStore.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/View/InfoStepView.swift
- 검색 API 연결
- 중복 검사 API 연결
- 카테고리 리스트 불러오는 API 연결
- 뷰에 카테고리 리스트 isEmpty 여부에 따른 분기 처리 추가
- CategoryChipsView Kingfisher Image로 변경
=>  Feat/#119 등록 지도 API 연결

Spoony-iOS/Spoony-iOS/Network/TargetType/DetailTargetType.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/DetailView/DetailView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/Model/DetailModel.swift
- close: #121
- 탐색 상세 뷰 API 연결 했습니다.
- DetailCategoryColorResponse API에 따라 변경 했습니다.
- Concurrency 작업은 다음 브랜치에서 작업 하겠습니다.
- DetailService View에 구현해 뒀는데, 리팩토링할때 파일 변경 하겠습니다.
=> [Feat] #121 - DetailView API 연결

Spoony-iOS/Spoony-iOS/Resource/Helper/PopupModifier.swift
- close: #133 
- 팝업 뷰 버튼 색상 변경
=> fix: #133 팝업 뷰 버튼 색상 변경

Spoony-iOS/Spoony-iOS/Resource/Helper/ToastModifier.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/DetailView/DetailView.swift
- close: #134
- 폰트 변경
- 토스트 메세지 투명도 변경
`DetailView.swift`
- 영공백 추가하고, custom 폰트로 변경
- 토스트 메세지 구현
```swift
Text("이자카야인데 친구랑 가서 안주만 5개 넘게 시킴.. 명성이 자자한 고등어 봉초밥은 꼭 시키세요! 입에 넣자마자 사르르 녹아 없어짐. 그리고 밤 후식 진짜 맛도리니까 밤 디저트 좋아하는 사람이면 꼭 먹어보기!".splitZeroWidthSpace())
.customFont(.body2m)
```
=> [Fix] #134 - detail QA 반영 했습니다.

Spoony-iOS/Spoony-iOS/Source/Feature/Explore/ExploreCell.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Report/Report.swift
=> chore: #159 문구 변경 반영

Spoony-iOS/Spoony-iOS/Source/Feature/Home/Components/PlaceHolderCardView/PlaceCard.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Home/Components/PlaceHolderCardView/PlaceImagesLayout.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Home/NMapView.swift
=> Feat/#166 지도 관련 QA 반영

Spoony-iOS/Spoony-iOS/Source/Feature/Detail/DetailView/DetailState.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/DetailView/DetailView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/DetailView/DetailViewStore.swift
- close: #169
- 이미지 갯수에 따른 로직 추가
- 서버통신 실패시 예외처리 추가
=> [Feat] #169 - 상세 화면 QA 이미지, 서버 통신 실패시 수정 사항 반영

Spoony-iOS/Spoony-iOS/Resource/Components/SpoonyTextEditor.swift, Spoony-iOS/Spoony-iOS/Resource/Components/SpoonyTextField.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/Store/ExploreState.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/RegisterState.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/RegisterStore.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/View/InfoStepView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/View/Register.swift
- close: #166 
- 이모지 입력되는 버그 수정
- V 이모지 or 몇 가지 이모지에서 아무것도 입력 안됐는데 count가 1 되는 현상 발생
`SpoonyTextField`
- 이모지 필터링하는 함수
```swift
func removeCharacters() -> String {
return .init(
unicodeScalars.filter { scalar in
let isEmoji = scalar.properties.isEmoji || scalar.properties.isEmojiPresentation
let isControlCharacter = scalar.value == 8203 || scalar.value == 8204 || scalar.value == 8205 || scalar.value == 0x200B
let isSpecialCharacter = scalar == "*" || scalar == "#"
let isInvisibleSpace = scalar.value == 0x200B || scalar.value == 0x200C || scalar.value == 0x200D  // Invisible space characters
return (!isEmoji && !isControlCharacter && !isInvisibleSpace) || scalar.properties.numericType == .decimal || isSpecialCharacter
}
.reduce(into: "") { $0 += String($1) }
)
}
```
위에 써둔 오류 다시 수정하겠습니다.
=>  [Fix] #166 - 이모지 입력 수정

Spoony-iOS/Spoony-iOS/Resource/Components/SpoonyTextField.swift, Spoony-iOS/Spoony-iOS/Resource/Extension/String+.swift
- close: #180 
- 특정 이모지 입력시 아무것도 입력 안되었지만 해당 text의 count가 1 증가하는 현상 수정
|    구현 내용    |   이전   |   이후   |
| GIF | <img src = "https://github.com/user-attachments/assets/d8a70a5d-396f-4922-bd73-8bfcbac68c59" width ="250"> | <img src = "https://github.com/user-attachments/assets/4ffd26f9-701b-4b18-94a8-c0ba4553e6b2" width ="250"> |
=>  [Fix] #180 - 특정 이모지 입력 버그 수정

Spoony-iOS/Info.plist, Spoony-iOS/Spoony-iOS/SpoonyApp.swift
- close: #197 
- 컨피그 파일 하나로 합치기
| GIF | <img src = "https://github.com/user-attachments/assets/c9f6d144-61f2-4d00-b14d-fb54bcba01cb" width ="250"> | <img src = "" width ="250"> |
디코에 통합 컨피그 파일로 올렷으니 그대로 수정해주세요!
=> feat: #197 config파일 통합

Spoony-iOS/Spoony-iOS/Resource/Assets.xcassets/Icon/ic_slider.imageset/Contents.json, Spoony-iOS/Spoony-iOS/Resource/Assets.xcassets/Icon/ic_slider.imageset/Group.svg, Spoony-iOS/Spoony-iOS/Resource/Components/SpoonySlider.swift
- close: #224 
- SpoonySlider 구현
- 드레그로 조절
- 탭으로 조절
|    구현 내용    |   IPhone 16 pro   |
| GIF | <img src = "https://github.com/user-attachments/assets/45a50642-db17-497d-a478-ac678460af44" width ="250"> |
- 사용법(디폴트 50)
```swift
@State var value = 50.0
SpoonySlider($value)
```
- 사용법(보기전용)
```swift
SpoonySlider(.constant(90), isDisabled: true)
```
=>  [Style/#224] SpoonySlider 컴포넌트 구현

Spoony-iOS/Spoony-iOS.xcodeproj/project.pbxproj, Spoony-iOS/Spoony-iOS/Resource/Components/FollowButton.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Following/FollowListView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Following/FollowResponseModel.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/MyPageView.swift
- close: #221
- 팔로잉 팔로워 뷰로직만 구현을 했습니다.
|    뷰 로직만 구현    |   IPhone 15 pro   |
| GIF | <img src = "https://github.com/user-attachments/assets/4fb470c3-c34d-4272-bbe0-1be2d0fc073f" width ="450"> |
- `FollowListView.swift`
레이아웃은 내부 보시면 이해될 거예요!
```swift
var body: some View {
VStack(spacing: 0) {
pageControlSection // 페이지 컨트롤
separatorSection // 중간 분리 뷰
listSection // 팔로잉, 팔로워 리스트
}
}
```
현재는 제 뷰밖에 없어서  `private var listSection: some View` 형식으로 구현을 했는데, 다른 곳에서 재사용 된다면 struct 로 컴포넌트화 해볼게요
`Namespace` 와 `matchedGeometryEffect`의 도움을 받고 구현을 했어요! 키워드는 공부하면 추후 애니메이션 구현할 때 도움 될 것 같아요!
`FollowButton.swift`
최대한 피그마에 보고 1px, 0.1px 조정하면서 만들었는데 비슷할지 모르겠네요!
처음에는 RadialGradient 로 구현을 했는데, EllipticalGradient 가 좀 더 적절해 보여서 수정했어요! (근데 둘다 비슷해요!)
| 개발 화면 | 피그마 디자인 | …
=> [Style] #221 - 팔로우 팔로잉 뷰 구현 했습니다.

Spoony-iOS/Spoony-iOS/Resource/Components/SpoonySlider.swift, Spoony-iOS/Spoony-iOS/Resource/Components/SpoonyTextEditor.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/TestScenes/MyPageCoordinator/MyPageCoordinator.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/MyPageView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Profile/ProfileView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/Components/PlaceInfoCell.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/Model/PlaceInfoType.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/InfoStepFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/RegisterFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/ReviewStepFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/View/InfoStepView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/View/Register.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/View/ReviewStepView.swift
- close: #244 
- SpoonySlider padding 삭제
- InfoStepFeature, ReviewStepFeature editState 구현
- Register 화면 수정 모드 추가
- 변경된 UI로 수정
|    구현 내용    |   IPhone 16 pro   |   IPhone 13 mini   |
| GIF | <img src = "https://github.com/user-attachments/assets/7ab85364-44ad-40d2-a2e3-c9e53ca1d7fa" width ="250"> | <img src = "https://github.com/user-attachments/assets/29df3b6a-c642-4e83-a2f0-b983e8b64adb" width ="250"> |
=> Style/#244 register view 변경

Spoony-iOS/Spoony-iOS/Resource/Components/PlaceHolderCardView/PlaceCard.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/MapCoordinator/MapCoordinator.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/MapCoordinator/MapCoordinatorView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Presentation/PostFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Presentation/PostView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Home/MapFeature.swift
- close: #262 
- 홈뷰 디테일 연결
| GIF | <img src = "https://github.com/user-attachments/assets/5b82c5e2-d25f-4949-923c-0eb19046089a" width ="250"> | <img src = "" width ="250"> |
=> [Feat/#262] 홈뷰 화면연결로직

Spoony-iOS/Spoony-iOS/Resource/Components/Navigation/CustomNavigationBar.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Search/SearchFeature/SearchFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Search/Views/RecentSearchesView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Search/Views/SearchView.swift
- close: #266 
- 검색하기 최근검색 눌러서 검색되게 수정
- 상단 칩 버튼 수정
| GIF | <img src = "https://github.com/user-attachments/assets/0867663d-7715-4db6-ab24-ddc69caec0a9" width ="250"> | <img src = "" width ="250"> |
=> [Feat/#266] 검색하기검색기록부분수정

Spoony-iOS/Spoony-iOS/Resource/Helper/Utilities.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/SettingFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/SettingsView.swift
- close: #271 
- 서비약관 개인정보처리방침 위치기반 이용약관 1ㄷ1문의 웹뷰연결
| GIF | <img src = "https://github.com/user-attachments/assets/3b3ead9c-51f5-47da-8f45-13f3d29d5a44" width ="250"> | <img src = "" width ="250"> |
config 변경된거 올렷으니 확인바랍니다
노션 페이지 나오면 그떄 해당 URL로 수정할 예정~
=> [Feat/#271] 마이페이지웹뷰연결하기

Spoony-iOS/Spoony-iOS/Network/DependencyKey/DetailUseCaseKey.swift, Spoony-iOS/Spoony-iOS/Network/DependencyKey/HomeServiceKey.swift, Spoony-iOS/Spoony-iOS/Network/DependencyKey/LoginServiceKey.swift, Spoony-iOS/Spoony-iOS/Network/DependencyKey/MyPageServiceKey.swift, Spoony-iOS/Spoony-iOS/Network/DependencyKey/RegisterServiceKey.swift, Spoony-iOS/Spoony-iOS/Resource/Extension/DependencyValues+.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/MapCoordinator/MapCoordinator.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Presentation/PostFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Home/MapFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Login/LoginFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Edit/EditProfileFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/RegisterFeature.swift
- close: #277 
- 파일 분리
enum도 여기다 하는게 좋을까요??
=> Chore/#277 dependency values파일분리

Spoony-iOS/Spoony-iOS/Network/Model/FeedResponse.swift, Spoony-iOS/Spoony-iOS/Network/Model/MyPageModel/UserInfoResponse.swift, Spoony-iOS/Spoony-iOS/Network/Service/MyPageService/MyPageService.swift, Spoony-iOS/Spoony-iOS/Network/TargetType/MyPageTargetType.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/Search/ExploreSearchFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/View/ExploreCell.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Profile/ProfileFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Profile/ProfileView.swift
- close: #279 
- 마이페이지 API 연결 
| GIF | <img src = "https://github.com/user-attachments/assets/12b0d884-34fe-4fe8-9341-83758e067439" width ="250"> | <img src = "" width ="250"> |
- 하 어렵다
=> [Feat/#279] 마이페이지로그인등연결

Spoony-iOS/Launch Screen.storyboard, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Setting/BlockedUsersFeature/BlockedUsersView.swift
- close: #285 
- 차단유저 UI 구현
| GIF | <img src = "https://github.com/user-attachments/assets/d82ae757-c736-4c56-b6f0-33f89c9e5316" width ="250"> | <img src = "" width ="250"> |
명진샘 코드 그대로 날먹했습니다 잘먹었습니다 
API 붙일때 모델이나 이런거 같이 파일분리할게요~
=> [Feat/#285] 미구현UI전부구현

Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Data/DataMapping/ReviewDetailResponseDTO.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Data/DataMapping/UserInfoResponseDTO.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Domain/Entity/ReviewDetailModel.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Domain/UseCase/DetailUseCase.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Presentation/DetailView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Presentation/DetailViewStore.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Presentation/MockDetailViewStore.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Presentation/PostFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Presentation/PostView.swift
- close: #286
- DTO 수정하여 서버 연결 원활하게 수정
|    구현 내용    |   IPhone 15 pro   | 
| 리뷰 상세 페이지 | <img src = "https://github.com/user-attachments/assets/2bdc74f3-d374-4b29-9155-f2cb71ac89b0" width ="400"> |
1. 상세 뷰는  `PostView.swift` 를 보면 됩니다! Detail은 제가 조만간 삭제 할게요
2. 전반적으로 DTO 만 수정 했습니다!!
=> [Fix/#286] postView 서버 연결 안되는 문제 해결

Spoony-iOS/Spoony-iOS/Network/Base/Providers.swift, Spoony-iOS/Spoony-iOS/Network/DependencyKey/ImageLoadServiceKey.swift, Spoony-iOS/Spoony-iOS/Network/Service/ImageLoadService.swift, Spoony-iOS/Spoony-iOS/Network/TargetType/ImageLoadTargetType.swift, Spoony-iOS/Spoony-iOS/Resource/Extension/DependencyValues+.swift
- close: #289 
- 네트워크 세팅
이렇게 Date 형으로 반환하게 하는게 맞을까요..?
=>  [Fix/#289] 이미지 토큰 필요시 네트워크 통신 구현

Spoony-iOS/Spoony-iOS/Network/Auth/UserManager.swift, Spoony-iOS/Spoony-iOS/Network/Model/RegisterModel/EditPostRequest.swift, Spoony-iOS/Spoony-iOS/Network/Model/RegisterModel/RegisterPostRequest.swift, Spoony-iOS/Spoony-iOS/Network/Model/RegisterModel/ReviewResponse.swift, Spoony-iOS/Spoony-iOS/Network/Service/RegisterService/RegisterService.swift, Spoony-iOS/Spoony-iOS/Network/TargetType/RegisterTargetType.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/TabCoordinator/TabCoordinator.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/TabCoordinator/TabCoordinatorView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/TestScenes/MyPageCoordinator/MyPageCoordinator.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/MyPageView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Profile/ProfileFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Profile/ProfileView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/Model/ReviewInfo.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/Model/UploadImage.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/InfoStepFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/RegisterFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/State/ReviewStepFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/View/Register.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Register/View/ReviewStepView.swift
- close: #257 
- 어쩌구저쩌구
|    구현 내용    |   IPhone 16 pro 등록   |   IPhone 16 pro 수정   |
| GIF | <img src = "https://github.com/user-attachments/assets/07af88b9-a131-48a9-8ca9-47d27ea5e9b6" width ="250"> | <img src = "https://github.com/user-attachments/assets/08960cb0-c550-480b-81f5-33ce1815ef79" width ="250"> |
탭바 없애는 로직은 좀 더 생각을 해봐야할 것 같습니다...
아직 디테일뷰 연결은 못했습니다
=>  [Feat/#257] 탐색 검색 api 연결

Spoony-iOS/Spoony-iOS/Network/Model/ExploreModel/FeedFilteredRequest.swift, Spoony-iOS/Spoony-iOS/Network/Model/ExploreModel/FilteredFeedResponse.swift, Spoony-iOS/Spoony-iOS/Network/Service/ExploreService.swift, Spoony-iOS/Spoony-iOS/Network/TargetType/ExploreTargetType.swift, Spoony-iOS/Spoony-iOS/Resource/Extension/Date+.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Presentation/PostView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/Enums/AgeType.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/ExploreCoordinator.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/ExploreCoordinatorView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/ExploreFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/Filtering/FilteringBottomSheet.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/Filtering/SortBottomSheet.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/Model/FilterInfo.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/Search/ExploreSearchView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/View/Explore.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Explore/View/ExploreCell.swift
- close: #284 
- 기능 명세 반영
- 뷰 이것저것 수정
- 탐색 api
- 디테일 뷰로 네비게이션 연결
- 현재 신고하기가 TCA가 안되어있어서 네비게이션 연결 못했습니다. 다른 브랜치에서 작업 완료했고 api만 붙이면 돼서 일단 이거 머지하고 새로 브랜치 파서 반영하도록 하겠습니다 ~!
- 현재 탐색 api (isMine, 지역 선택 오류, 페이지네이션) 서버에서 변경 중이라 완벽하지 않습니다.. 추후 브랜치에서 반영하겠습니다 !
=> [Feat/#284] 탐색 필터링 api

Spoony-iOS/Spoony-iOS/Network/Model/MyPageModel/ProfileImageResponse.swift, Spoony-iOS/Spoony-iOS/Network/Model/MyPageModel/UserProfileResponse.swift, Spoony-iOS/Spoony-iOS/Network/Service/MyPageService/MyPageService.swift, Spoony-iOS/Spoony-iOS/Resource/Components/BottomSheet/ProfileImageBottomSheet.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Edit/EditProfileFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Edit/EditProfileView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Model/ProfileImage.swift, Spoony-iOS/Spoony-iOS/Source/Feature/MyPage/Model/ProfileInfo.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Onboarding/NicknameTextField.swift
- close: #257 
- 프로필 수정 api 연결
- 닉네임 텍스트 필드 폰트 색상 변경
- 이미지 분기 처리
|    구현 내용    |   IPhone 16 pro   |   IPhone SE   |
| GIF | <img src = "https://github.com/user-attachments/assets/f2a8eca5-4494-4415-8a71-65f8abf3c671" width ="250"> | <img src = "" width ="250"> |
시연 영상의 프로필 사진은 테스트용으로 넣어뒀습니다.
지금 서버에서 1개만 주고 있어서 한 번 확인해봐야할 것 같습니다
=>  [Feat/#257] 프로필 수정 api 연결

Spoony-iOS/Spoony-iOS/Network/Auth/UserManager.swift, Spoony-iOS/Spoony-iOS/Resource/Components/SpoonyDraw/SpoonDrawPopupView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Home/Home.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Home/MapFeature.swift
- close: #315 
- 디버그 버튼 추가
- 뷰 등장시 전체화면으로 수정
- 유저디폴트에 기본값으로 정의
| GIF | <img src = "https://github.com/user-attachments/assets/7c60fb0f-568b-4072-b8f5-f5d899e9423f" width ="250"> | <img src = "" width ="250"> |
하루 계산 로직 설명
```swift
func isFirstVisitOfDay() -> Bool {
let today = Calendar.current.startOfDay(for: Date())
if let lastVisitDate = lastAppVisitDate {
let lastVisitDay = Calendar.current.startOfDay(for: lastVisitDate)
// 마지막 방문일이 오늘 이전이면 첫 방문으로 간주
if lastVisitDay < today {
lastAppVisitDate = today
return true
}
return false
} else {
// 첫 방문 (lastAppVisitDate가 nil)
lastAppVisitDate = today
return true
}
}
```
오늘 날짜의 시작 시간(자정) 가져오기
```swift
let today = Calendar.current.startOfDay(for: …
```
=> [Feat/#315] 스푼뽑기컴포넌트연결

Spoony-iOS/Spoony-iOS/Network/TargetType/DetailTargetType.swift, Spoony-iOS/Spoony-iOS/Network/TargetType/FollowTargetType.swift, Spoony-iOS/Spoony-iOS/Network/TargetType/HomeTargetType.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Data/Repository/DetailRepository.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Data/Service/DetailService.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Domain/RepositoryInterface/DetailRepositoryInterface.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Domain/UseCase/DetailUseCase.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Presentation/MockDetailUseCase.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Presentation/PostFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Detail/Presentation/PostView.swift
- close: #323
- 리뷰 상세 팔로잉 로직 수정
- 유저 남의 정보 가져오는 API 추가
|    팔로워 팔로잉 테스트 성공 |   IPhone 15 pro   | 
| GIF | <img src = "https://github.com/user-attachments/assets/6d2ff5ec-0802-46b3-ae16-2d0c7bd05e9d" width ="250"> |
- 하 에러 여기저기에서 catch 하니까 하나로 통일 마렵다
- 팔로잉 할때 서버 통신 성공하면 진동 햅틱 줄까????
=> [Fix/#323] 리뷰 상세 팔로잉 로직 수정

Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/AppCoordinator/AppCoordinator.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/TabRootCoordinator/TabRootCoordinator.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Setting/AccountManagement/AccountManagementFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Setting/AccountManagement/AccountManagementView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Setting/AccountManagement/withdraw/WithdrawFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Setting/AccountManagement/withdraw/WithdrawView.swift
- close: #344 
- 로그아웃 안되는 오류 해결
- 회원탈퇴 안되는 오류 해결
- 로그인 타입이 어떤건지 동적매칭
핫픽스이기에 부연설명은 생략합니다
=> [Feat/#344] 로그아웃고치기

Spoony-iOS/Spoony-iOS/Network/Auth/UserManager.swift, Spoony-iOS/Spoony-iOS/Resource/Components/SpoonyDraw/SpoonDrawPopupView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Home/Home.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Home/MapFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Home/NMapView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Attendance/AttendanceFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Attendance/AttendanceView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Attendance/SpoonAttendanceView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Onboarding/OnboardingFeature.swift
=> Fix/#352 스푼뽑기qa오류해결

Spoony-iOS/Spoony-iOS/Network/Model/BlockUserModel.swift, Spoony-iOS/Spoony-iOS/Network/Model/ExploreModel/FilteredFeedResponse.swift, Spoony-iOS/Spoony-iOS/Network/Model/ExploreModel/ReviewSearchListResponse.swift, Spoony-iOS/Spoony-iOS/Network/Model/FeedResponse.swift, Spoony-iOS/Spoony-iOS/Network/Model/MyPageModel/UserInfoResponse.swift, Spoony-iOS/Spoony-iOS/Network/Model/MyPageModel/UserProfileResponse.swift, Spoony-iOS/Spoony-iOS/Resource/Components/BottomSheet/LocationPickerBottomSheet.swift, Spoony-iOS/Spoony-iOS/Resource/Components/SpoonyTextEditor.swift, Spoony-iOS/Spoony-iOS/Resource/Extension/Date+.swift, Spoony-iOS/Spoony-iOS/Resource/Helper/AlertModifier.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/ExploreFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/Filtering/FilteringBottomSheet.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/Model/FeedEntity.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/Search/ExploreSearchFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/Search/ExploreSearchView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/View/Explore.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/View/ExploreCell.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/OtherProfile/OtherProfileFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Profile/ProfileFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Setting/BlockedUsersFeature/BlockedUsersView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Onboarding/OnboardingFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Data/DataMapping/UserInfoResponseDTO.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Presentation/PostFeature.swift
- close: #359 
- 온보딩, 탐색 QA 반영
-  등록할 때 사진 선택 풀림 이슈
-> 타임어택으로 사진 풀리기 전에 따닥하고 등록하면 등록이 되긴 함.. 
-> but ! ! 저 현상이 발생 하기도 전에 사진 고르기 뷰 뜨자마자 사진 선택하고 등록하면 정상 등록이 되지만 explorecell에서 메뉴버튼이 안눌리는 이슈가 있음 이유를 도저히 모르겠음....
|    구현 내용    |   IPhone 15 pro   | 
| GIF | <img src = "https://github.com/user-attachments/assets/3fff22cb-0a39-4819-83c5-f8057961353e" width ="250"> |
- alert 수정했는데 약간 깜빡거리는 것 같기도... ㅠㅠ
|    구현 내용    |   IPhone 15 pro   | 
| GIF | <img src = "https://github.com/user-attachments/assets/bcbc8480-de41-4303-b5ef-e40021c08fb0" width ="250"> |
=> [Bug/#359] QA 반영

Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/MyPageCoordinator/MyPageCoordinator.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/TabCoordinator/TabCoordinator.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Following/FollowFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Following/FollowListView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/OtherProfile/OtherProfileFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/OtherProfile/OtherProfileView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Profile/ProfileFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Profile/ProfileView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Setting/BlockedUsersFeature/BlockedUsersFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Setting/BlockedUsersFeature/BlockedUsersView.swift
- close: #367 
- 디자인 스펙을 맞췃습니다
- 토스트 메세지를 수정햇습니다
- 차단 해제시 바로 사라지는것이 아닌 pulltoRefresh를 도입햇습니다
- 상세페이지로 이동하는 피쳐를 구현햇습니다
=> [Fix/#367] 마이페이지QA

Spoony-iOS/Spoony-iOS/Resource/Helper/ToastModifier.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Data/DataMapping/PostResponseDTO.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Domain/Entity/PostModel.swift
- close: #353
- DTO 수정 ( 옵셔널로 오는 값 옵셔널로 수정만 함)
- 토스트 메세지 수정
|    종류  |   토스트 메세지   |
| :-------------: | :----------: | 
| GIF | ![화면 기록 2025-06-09 오후 11 35 29](https://github.com/user-attachments/assets/d113c5a7-632e-4c9a-869e-86f2a72a4ca7) | 
`ToastModifier.swift`
-  위 파일에서 Text 속성만 변경 하였습니다.
```swift
Text(message)
.foregroundStyle(.white)
.font(.body2m)
.lineLimit(nil)
.multilineTextAlignment(.leading)
.fixedSize(horizontal: false, vertical: true)
.padding(.vertical, 12)
.padding(.horizontal, 16)
```
- 특정 데이터 일때 안되는거 좀 더 봐봐야할듯, 코드상으로는 어떤게 문제가 되는지 모르겠습니다.
=> [Fix/#353] - 리뷰 상세 QA 진행 하였습니다.

Spoony-iOS/Spoony-iOS/Network/Model/ExploreModel/UserSimpleResponse.swift, Spoony-iOS/Spoony-iOS/Resource/Helper/DateFormatterHelpers.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/ExploreCoordinator/ExploreCoordinator.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/ExploreCoordinator/ExploreCoordinatorView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/MyPageCoordinator/MyPageCoordinator.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/TabCoordinator/TabCoordinator.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/TabRootCoordinator/TabRootCoordinator.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/TabRootCoordinator/TabRootCoordinatorView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/Model/SimpleUser.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/Search/ExploreSearchFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/Search/ExploreSearchView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Following/FollowFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Following/FollowListView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Following/FollowResponseModel.swift
- close: #378 
- 검색, 팔로우/팔로잉에서 본인인 경우 처리
=> [Fix/#378] ismine

Spoony-iOS/Spoony-iOS/Resource/Components/BottomSheet/ProfileImageBottomSheet.swift
- close: #387 
- 글 짤림 현상 수정
|    구현 내용    |   전   |   후   |
| GIF | <img src = "https://github.com/user-attachments/assets/b6186e2f-7b97-4352-bb9b-b561fec1946b" width ="250"> | <img src = "https://github.com/user-attachments/assets/01ce6f0d-c367-4cad-b9b9-16526f7cfdea" width ="250"> |
=> [Fix: #387] - 글 짤림 현상 수정

Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Attendance/AttendanceFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Presentation/PostFeature.swift
- close: #394 
- 
- ## 📄 작업 내용
- 유저디폴트 저장
- 사과문 작성
=> [Fix/#394] 스푼뽑기 수정

Spoony-iOS/Spoony-iOS/Network/Model/MyPageModel/EditProfileRequest.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Edit/EditProfileFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Edit/EditProfileImageView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Edit/EditProfileView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Edit/ProfileImageType.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Following/FollowFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Following/FollowListView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Presentation/PostFeature.swift
- close: #397 
- 락 이미지 안나오는 이슈 해결
- 프로필 수정 지역 설정 안했는데 디폴트 값 저장되는 현상 해결
=> Fix/#397 대면qa

Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Following/FollowFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Following/FollowListView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Post/Presentation/PostView.swift
- close: #402 
- 아래 스크린샷 QA 해결함
=> [Fix/#401] - 굿모닝 QA

Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Register/State/RegisterFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Register/View/Register.swift
- close: #405 
- post 요청중 뒤로가기 버튼 클릭 가능 현상 수정
=> [fix: #405]post 요청중 뒤로가기 버튼 클릭 가능 현상 수정

Spoony-iOS/Spoony-iOS/Network/Service/MyPageService/MyPageService.swift, Spoony-iOS/Spoony-iOS/Network/TargetType/MyPageTargetType.swift, Spoony-iOS/Spoony-iOS/Resource/Components/PlaceHolderCardView/PlaceCard.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/MapCoordinator/MapCoordinator.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Home/Home.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Home/NMapView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Attendance/AttendanceInfoSheetView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/Attendance/AttendanceView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/OtherProfile/OtherProfileFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/MyPage/OtherProfile/OtherProfileView.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/SearchLocation/SearchLocationFeature.swift
- close: #404 
- 2차 QA에 올라온 리스트들을 수정했습니다.
=> Fix/#404 2차수정qa이지훈

Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/ExploreCoordinator/ExploreCoordinator.swift
- close: #이슈번호
- 어쩌구저쩌구
- 어쩌구저쩌구
```swift
```
=> fix: #410 뒤로가기 연결

Spoony-iOS/Spoony-iOS/Network/Model/RegisterModel/RegisterPostRequest.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Register/State/RegisterFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Register/View/Register.swift
=> [fix: #408] 22일QA반영

Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/MapCoordinator/MapCoordinator.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Coordinator/TabCoordinator/TabCoordinator.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Home/Home.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Home/MapFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/SearchLocation/SearchLocationFeature.swift
- close: #이슈번호
- 어쩌구저쩌구
- 어쩌구저쩌구
```swift
```
=> Fix/#409 2차qa오류잡기

Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Explore/View/ExploreCell.swift
- close: #이슈번호
- 어쩌구저쩌구
- 어쩌구저쩌구
```swift
```
=> fix: #416 메뉴 드롭다운 수정

Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Login/LoginFeature.swift
- close: #430
- 어쩌구저쩌구
- 어쩌구저쩌구
```swift
```
=> Fix/#430 isLoading 없앰

Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Login/LoginFeature.swift, Spoony-iOS/Spoony-iOS/Source/Feature/Scene/Login/View/LoginView.swift
- close: #438 
- UI에 버튼 다시 올렸습니다.
- 로그인-회원가입-회원탈퇴 로직 잘 동작하는 거 확인했습니다.
- 테플에 올려서 확인 해봅시듀듀
=> Chore/#438 카카오 로그인 버튼 다시 올려두었습니다..
